import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Card from '../components/Card';
import HeaderCard from '../components/HeaderCard';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <div className={styles.mainContent}>
        <Card />
        <HeaderCard text="this is a test!" />
      </div>
      <Image
        src="/beach_backdrop.svg"
        alt="beach drawing"
        layout="fill"
        objectFit="cover"
      />
    </main>
  </div>
);

export default Home;
